[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = direct

lib_deps =
    h2zero/NimBLE-Arduino@^2.2.0

build_flags =
    -std=c++17
    -I ../../../include
    -D EVENG1_PLATFORM_ESP32

board_build.partitions = default.csv
